const glossary = [
  { term: 'Artificial Intelligence (AI)', definition: 'Software that imitates human behaviors and capabilities including learning, reasoning, and problem-solving.', category: 'AI Workloads & Responsible AI' },
  { term: 'Machine Learning', definition: 'A subset of AI where models learn patterns from data to make predictions without being explicitly programmed.', category: 'AI Workloads & Responsible AI' },
  { term: 'Computer Vision', definition: 'AI workload that interprets visual information from images and video.', category: 'AI Workloads & Responsible AI' },
  { term: 'Natural Language Processing (NLP)', definition: 'AI workload that enables computers to understand, interpret, and generate human language.', category: 'AI Workloads & Responsible AI' },
  { term: 'Document Processing', definition: 'AI workload that extracts structured information from documents like invoices, receipts, and forms.', category: 'AI Workloads & Responsible AI' },
  { term: 'Generative AI', definition: 'AI that creates original content - text, images, code - rather than just analyzing existing data.', category: 'AI Workloads & Responsible AI' },
  { term: 'Fairness', definition: 'Responsible AI principle: AI should treat all groups of people equitably without discrimination based on race, gender, etc.', category: 'AI Workloads & Responsible AI' },
  { term: 'Reliability & Safety', definition: 'Responsible AI principle: AI should perform reliably and safely under normal and unexpected conditions.', category: 'AI Workloads & Responsible AI' },
  { term: 'Privacy & Security', definition: 'Responsible AI principle: AI should handle data securely and protect individual privacy.', category: 'AI Workloads & Responsible AI' },
  { term: 'Inclusiveness', definition: 'Responsible AI principle: AI should address a broad range of human needs and be accessible to people with disabilities.', category: 'AI Workloads & Responsible AI' },
  { term: 'Transparency', definition: 'Responsible AI principle: AI systems should be understandable - users should know how decisions are made.', category: 'AI Workloads & Responsible AI' },
  { term: 'Accountability', definition: 'Responsible AI principle: People who design and deploy AI must be answerable for how their systems operate.', category: 'AI Workloads & Responsible AI' },
  { term: 'FAIR-PT', definition: 'Mnemonic for the 6 responsible AI principles: Fairness, Accountability, Inclusiveness, Reliability & Safety, Privacy & Security, Transparency.', category: 'AI Workloads & Responsible AI' },
  { term: 'Azure AI Services', definition: "Umbrella term for Microsoft's pre-built AI APIs (formerly Cognitive Services). Can be multi-service (one key for all) or single-service resources.", category: 'AI Workloads & Responsible AI' },
  { term: 'Multi-service resource', definition: 'One Azure AI Services resource with a single key and endpoint that provides access to multiple AI services.', category: 'AI Workloads & Responsible AI' },
  { term: 'Single-service resource', definition: 'A dedicated Azure resource for one specific AI service (e.g., just Vision or just Language) with its own key and endpoint.', category: 'AI Workloads & Responsible AI' },

  { term: 'Regression', definition: 'ML technique that predicts a continuous numeric value (e.g., price, temperature, sales). Key metrics: MAE, RMSE, R2.', category: 'Machine Learning Fundamentals' },
  { term: 'Classification', definition: 'ML technique that predicts a category/class label (e.g., spam/not spam, disease type). Key metrics: accuracy, precision, recall, F1-score.', category: 'Machine Learning Fundamentals' },
  { term: 'Clustering', definition: 'Unsupervised ML technique that groups similar data points without labeled data. Key metric: Silhouette score.', category: 'Machine Learning Fundamentals' },
  { term: 'Features', definition: 'The input columns/variables used to train a model (e.g., square footage, number of bedrooms).', category: 'Machine Learning Fundamentals' },
  { term: 'Labels', definition: 'The target value the model is trained to predict (e.g., house price, spam/not spam).', category: 'Machine Learning Fundamentals' },
  { term: 'Training dataset', definition: 'The portion of data used to teach the model patterns. Typically 70-80% of total data.', category: 'Machine Learning Fundamentals' },
  { term: 'Validation dataset', definition: 'The portion of data used to evaluate model performance during training. Typically 20-30% of total data.', category: 'Machine Learning Fundamentals' },
  { term: 'Deep Learning', definition: 'Advanced ML using artificial neural networks with multiple layers, inspired by the human brain. Used for complex pattern recognition.', category: 'Machine Learning Fundamentals' },
  { term: 'Transformer', definition: 'Neural network architecture that uses self-attention mechanisms. Foundation of GPT, BERT, and all modern LLMs. NEW on exam.', category: 'Machine Learning Fundamentals' },
  { term: 'Self-attention', definition: 'Mechanism in Transformers that lets the model weigh the importance of different parts of the input relative to each other.', category: 'Machine Learning Fundamentals' },
  { term: 'Azure Machine Learning', definition: 'Cloud service for the full ML lifecycle: data prep, training, evaluation, deployment, and monitoring.', category: 'Machine Learning Fundamentals' },
  { term: 'AutoML', definition: 'Azure ML feature that automatically tries multiple algorithms and hyperparameters to find the best model.', category: 'Machine Learning Fundamentals' },
  { term: 'Azure ML Designer', definition: 'Drag-and-drop visual interface for building ML pipelines without code.', category: 'Machine Learning Fundamentals' },
  { term: 'Inference', definition: 'Using a trained model to make predictions on new, unseen data.', category: 'Machine Learning Fundamentals' },
  { term: 'Overfitting', definition: 'When a model performs well on training data but poorly on new data - it memorized instead of learning patterns.', category: 'Machine Learning Fundamentals' },
  { term: 'Mean Absolute Error (MAE)', definition: 'Regression metric: average absolute difference between predicted and actual values. Lower = better.', category: 'Machine Learning Fundamentals' },
  { term: 'R2 (R-squared)', definition: 'Regression metric: proportion of variance explained by the model. 1.0 = perfect, 0 = no better than average.', category: 'Machine Learning Fundamentals' },
  { term: 'F1-score', definition: 'Classification metric: harmonic mean of precision and recall. Balances both for overall accuracy.', category: 'Machine Learning Fundamentals' },
  { term: 'Silhouette score', definition: 'Clustering metric: measures how similar points are to their own cluster vs other clusters. Range -1 to 1, higher = better.', category: 'Machine Learning Fundamentals' },
  { term: 'Feature Engineering', definition: 'Creating new input features from existing data to improve model performance.', category: 'Machine Learning Fundamentals' },

  { term: 'Image Classification', definition: "Identifies WHAT is in an image by assigning a label/tag (e.g., 'cat', 'dog', 'car').", category: 'Computer Vision' },
  { term: 'Object Detection', definition: 'Identifies WHAT and WHERE objects are in an image using bounding boxes with labels.', category: 'Computer Vision' },
  { term: 'OCR (Optical Character Recognition)', definition: 'Extracts text from images. Azure AI Vision Read API organizes results as Pages -> Lines -> Words.', category: 'Computer Vision' },
  { term: 'Azure AI Vision', definition: 'Service for image analysis: captions, tags, object detection, OCR, smart cropping. Formerly Computer Vision.', category: 'Computer Vision' },
  { term: 'Custom Vision', definition: 'Service for training your own image classification or object detection models with your labeled images.', category: 'Computer Vision' },
  { term: 'Azure AI Face', definition: 'Service for face detection and analysis: accessories, blur, exposure, glasses, head pose, mask, noise, occlusion.', category: 'Computer Vision' },
  { term: 'Face Detection vs Recognition', definition: 'Detection = finding faces in an image. Recognition = identifying WHO a face belongs to (more restricted).', category: 'Computer Vision' },
  { term: 'CNN (Convolutional Neural Network)', definition: 'Neural network architecture commonly used for image classification and computer vision tasks.', category: 'Computer Vision' },
  { term: 'Azure AI Document Intelligence', definition: 'Extracts structured data from documents (invoices, receipts, IDs). Has prebuilt and custom models. Formerly Form Recognizer.', category: 'Computer Vision' },

  { term: 'Sentiment Analysis', definition: 'Determines if text is positive, negative, or neutral. Part of Azure AI Language service.', category: 'Natural Language Processing' },
  { term: 'Key Phrase Extraction', definition: 'Identifies the main talking points in text. Part of Azure AI Language service.', category: 'Natural Language Processing' },
  { term: 'Entity Recognition (NER)', definition: 'Identifies and categorizes entities in text: people, places, organizations, dates, quantities.', category: 'Natural Language Processing' },
  { term: 'Language Detection', definition: 'Identifies which language a text document is written in. Part of Azure AI Language service.', category: 'Natural Language Processing' },
  { term: 'Azure AI Language', definition: 'Service for text analytics: sentiment, key phrases, entities, language detection, summarization, custom classification.', category: 'Natural Language Processing' },
  { term: 'CLU (Conversational Language Understanding)', definition: 'Service for understanding user intents and extracting entities from natural language. Formerly LUIS.', category: 'Natural Language Processing' },
  { term: 'Intent', definition: "The purpose or goal expressed in a user's utterance (e.g., 'BookFlight', 'CancelReservation').", category: 'Natural Language Processing' },
  { term: 'Entity', definition: "An item or concept that an utterance refers to (e.g., 'Seattle', 'tomorrow', '2 tickets').", category: 'Natural Language Processing' },
  { term: 'Utterance', definition: 'An example of something a user might say that the language model must interpret.', category: 'Natural Language Processing' },
  { term: 'Custom Question Answering', definition: 'Creates FAQ-style conversational bots from documents, URLs, or manual Q&A pairs. Formerly QnA Maker.', category: 'Natural Language Processing' },
  { term: 'Azure AI Speech', definition: 'Service for speech-to-text (recognition) and text-to-speech (synthesis).', category: 'Natural Language Processing' },
  { term: 'Azure Translator', definition: 'Service for real-time text translation between 100+ languages.', category: 'Natural Language Processing' },
  { term: 'Azure Bot Service', definition: 'Framework for building and deploying conversational bots across channels: webchat, Teams, email, Slack.', category: 'Natural Language Processing' },
  { term: 'Azure AI Search', definition: 'Search service with AI enrichment (skillsets) for extracting insights from unstructured data. Formerly Cognitive Search.', category: 'Natural Language Processing' },
  { term: 'Skillset', definition: 'In Azure AI Search, a sequence of AI enrichment skills applied during indexing (e.g., OCR, entity extraction, key phrases).', category: 'Natural Language Processing' },
  { term: 'Knowledge Mining', definition: 'Using AI to automatically extract information and insights from large volumes of unstructured data.', category: 'Natural Language Processing' },
  { term: 'Tokenization', definition: 'Breaking text into individual tokens (words or subwords) for NLP or LLM processing.', category: 'Natural Language Processing' },

  { term: 'Large Language Model (LLM)', definition: 'Deep learning model trained on massive text data that can generate, summarize, translate, and reason about text. Examples: GPT-4, LLaMA.', category: 'Generative AI' },
  { term: 'Azure OpenAI Service', definition: "Microsoft's enterprise platform for deploying OpenAI models (GPT-4, DALL-E, Embeddings) with Azure security and compliance.", category: 'Generative AI' },
  { term: 'Microsoft Foundry', definition: 'Unified AI development platform (formerly Azure AI Studio) with access to 1,600+ models. Integrates with Azure ML. NEW on exam.', category: 'Generative AI' },
  { term: 'Foundry Model Catalog', definition: 'Browsable catalog of 1,600+ models from Microsoft, OpenAI, Meta, Hugging Face and others. Filter and compare before deploying. NEW on exam.', category: 'Generative AI' },
  { term: 'GPT', definition: "Generative Pre-trained Transformer. OpenAI's text generation model family. GPT-4 is the latest.", category: 'Generative AI' },
  { term: 'DALL-E', definition: "OpenAI's image generation model. Creates images from text descriptions.", category: 'Generative AI' },
  { term: 'Embeddings', definition: 'Vector representations of text that capture semantic meaning. Used for similarity search, RAG, and recommendations.', category: 'Generative AI' },
  { term: 'Prompt Engineering', definition: 'The practice of crafting inputs (prompts) to get better, more accurate outputs from AI models.', category: 'Generative AI' },
  { term: 'Temperature', definition: 'Prompt parameter (0-1) controlling randomness. 0 = deterministic/factual. 1 = creative/random.', category: 'Generative AI' },
  { term: 'top_p', definition: 'Prompt parameter controlling probability sampling. Lower values make output more focused and deterministic.', category: 'Generative AI' },
  { term: 'max_tokens', definition: "Prompt parameter that limits the length of the model's response.", category: 'Generative AI' },
  { term: 'Zero-shot prompting', definition: "Giving the model a task with no examples. Relies on the model's pre-trained knowledge.", category: 'Generative AI' },
  { term: 'Few-shot prompting', definition: "Including example input-output pairs in the prompt to guide the model's response format and style.", category: 'Generative AI' },
  { term: 'System message', definition: 'Instructions given to the model that define its behavior, persona, and constraints. Part of the metaprompt layer.', category: 'Generative AI' },
  { term: 'RAG (Retrieval-Augmented Generation)', definition: 'Pattern that retrieves relevant documents and includes them in the prompt to ground responses in factual data and reduce hallucinations.', category: 'Generative AI' },
  { term: 'Grounding', definition: 'Connecting model responses to specific, verifiable data sources to improve accuracy.', category: 'Generative AI' },
  { term: 'Hallucination', definition: 'When an AI model generates confident but factually incorrect or fabricated information.', category: 'Generative AI' },
  { term: 'Content Filters', definition: "Azure OpenAI's built-in safety system that detects and blocks harmful content (hate, violence, sexual, self-harm).", category: 'Generative AI' },
  { term: 'Copilot', definition: "Microsoft's AI assistant brand integrated into products (Microsoft 365, GitHub, etc.) to help users with everyday tasks.", category: 'Generative AI' },
  { term: 'Metaprompt & Grounding Layer', definition: 'The layer in a GenAI solution that handles prompt construction, system messages, and grounding data.', category: 'Generative AI' },
  { term: 'Safety System Layer', definition: 'Platform-level configurations (content filters, abuse monitoring) that mitigate harm in GenAI solutions.', category: 'Generative AI' },
  { term: 'Transparency Notes', definition: 'Microsoft documentation explaining how AI technology is built and asking users to consider its implications. Part of responsible GenAI.', category: 'Generative AI' },
]

export default glossary
